concord-consortium/storyq-codap-plugin

src/components/target_text_area.tsx
src/storyq.css

Fixed CSS so that text boxes can scroll in target tab and are responsive to height and width adjustments of the component.

Make text boxes scroll in target tab.

---

src/storyq.css

I was unable to get finish with the scrolling behavior on other tabs. The "target" tab should work correctly, though, and the bottom message is correct.

Always display info prompt and constrain text columns in target tab to visual region.

---

src/components/storyq.tsx
src/components/testing_panel.tsx

This fixes an issue with the case creation notification not running when this plugin is included in a CODAP document and the plugin is collapsed (minimized) at load time.  This manifested as predictions not being updated when new cases were created in the testing table in the "Exploring AI in ELA with StoryQ (SY 2022)" sequence as the plugin was collapsed on page 4 in the first activity.
The tab component in the root Storyq component was not rendering the TestingPanel when the plugin was collapsed and the TestingPanel setup the CODAP case creation listener.
This fix pulls the testing manager instance creation and case creation listener into the root component and passes them down to the TestingPanel.  This allows the case creation notification to be handled when the plugin is collapsed.

fix: CODAP case creation notification listener not setup when plugin starts as collapsed [PT-185324855]

---

src/components/feature_panel.tsx

PT Story: https://www.pivotaltracker.com/story/show/188232760
This PR removes the Target Info Pane from the Feature Tab.

188232760 Remove the header from the feature tab

---

src/components/feature_pane.tsx
src/components/storyq.tsx
src/lib/codap-helper.ts
src/managers/headings_manager.ts
src/managers/text_feedback_manager.ts
src/stores/domain_store.ts
src/stores/feature_store.ts
src/stores/target_store.ts

PT Story: https://www.pivotaltracker.com/story/show/188150453
This PR updates StoryQ so it works in Codap v3.
- A feature must now be passed to `addFeatureUnderConstruction()`. I'm still not sure why this was not working with the old system, where `addFeatureUnderConstruction` was referencing `FeatureStore.featureUnderConstruction` directly.
- `getCaseValues` can now accept a formula argument. This allows `updateFrequenciesUsagesAndFeatureIDs` in `domain_store.ts` to specify that it only wants cases that fulfill the feature's requirements. I'm still not sure how this was ever working before!
- Cleans up the way headers are constructed in `fillInHeading` in `headings_manager.ts`.
- `{}` are removed as children, as Slate doesn't like that any more.
- If no headings are specified, an empty …

188150453 StoryQ in v3

---

src/stores/feature_store.ts
src/stores/target_store.ts
src/utilities/utilities.ts

This updates the plugin to pass the full trimmed text when pattern matching text and then changes the word boundary metacharacters in the pattern to be optional if the text begins/ends with non-word characters.
This also adds a missing escape of any regex characters in the free form text and changes spaces to match multiple spaces.

feat: Extract phrases and emoticons [PT-188319600] [PT-188319636]

---

src/managers/headings_manager.ts

PT Story: https://www.pivotaltracker.com/story/show/188364196
In some circumstances, StoryQ was still sending a slate object `{}` to a text tile. In modern slate, `{ text: "" }` is the blank object, and an empty `{}` causes the library to crash.

188364196 Fix Text Crash

---

src/storyq.css

This was missed in the removal of the devextreme plugin as it updated the body class which then changed the h1 font-size.

fix: Set h1 font-size [PT-188328210]

---

src/stores/feature_store.ts

PT Story: https://www.pivotaltracker.com/story/show/188381232
Previously, only datasets with a single collection and a single attribute could be used as a word list for the contains feature. This PR removes these restrictions, making all tables potentially word lists. The first attribute of the first collection if more than one is present.

188381232 Include All Tables As Potential Word Lists

---

src/components/training_pane.tsx

It was set to change on enter which made it look like the train button was broken if you entered a name and then used the mouse to click on the train button.

Fix: Change training name to update with each keypress [PT-188328210]

---

src/components/feature_component.tsx
src/stores/feature_store.ts

PT Story: https://www.pivotaltracker.com/n/projects/2441249/stories/188381232/comments/242731583
This PR follows up on https://github.com/concord-consortium/storyq-codap-plugin/pull/15 by making the first attribute of the _rightmost_ collection be the source of a word list, rather than the _leftmost_ collection.
It also makes the word list dropdown update properly.

188381232 Use Attribute from Rightmost Collection as Word List

---

src/components/feature_component.tsx
src/components/training_pane.tsx
src/components/ui/text-box.tsx

This simplifies the text box component to remove the unneeded keyup handler that was not being called when the Mac emoji tool (Control+Command+Space) was used to enter a character.
The keyup handler is no longer needed as the valueChangeEvent is always "keyup", whereas in the original UI it used keyup and enter.

fix: Emoji key combinations don't enable the feature done button [PT-188413736]

---

src/components/feature_component.scss
src/components/feature_component.tsx

This PR sets a minimum width for the word list dropdown on the features panel. This ensures that the list always appears on a second line, even if the names of the datasets in it are short.

188381232 Word List on Second Line

---

src/stores/domain_store.ts

The default precision seems to be 2 decimal places in CODAP v2 and 3 in CODAP v3 so the precision needs to be set explicitly to 2.

fix: Set model weight display precision to 2 decimal places [PT-188364442]

---

src/components/feature_component.tsx
src/lib/one_hot.ts
src/lib/stop_words.ts
src/lists/lists.ts
src/managers/model_manager.ts
src/managers/text_feedback_manager.ts
src/stores/feature_store.ts
src/stores/store_types_and_constants.ts
src/utilities/utilities.test.ts
src/utilities/utilities.ts

Jira story: https://concord-consortium.atlassian.net/browse/STORYQ-4
This PR improves highlighting of keywords in the new plugin text pane. The main improvement is that phrases are now highlighted, rather than just single words, but there are other improvements.
- Capitalization and whitespace is now preserved when highlighting.
- Words from word list features are now highlighted. These can be from built in word lists (`personalPronouns` and `prepositions`) or word lists from datasets (which just take the text in the first attribute).
Some relevant details related to the above changes:
- `allTokenizer` has been added to `one_hot.ts`, which breaks a text into tokens and whitespace. This is used by functions that display text to the user, rather than `wordTokenizer`, which is still used by …

Storyq-4 Highlighting

---

src/stores/feature_store.ts
src/stores/store_types_and_constants.ts
src/stores/target_store.ts
src/utilities/utilities.test.ts
src/utilities/utilities.ts

Jira Story: https://concord-consortium.atlassian.net/browse/STORYQ-12
This PR expands highlighting in StoryQ to include numbers and punctuation. Both cases are covered by a jest test. Both of these cases are similar to general text, but don't include quotes in the name (`contain: "word"` vs `contain: !` or `contain: anyNumber`). This is also the pattern followed by lists. So now, if a list isn't found, we check to determine if we're looking for the `anyNumber` keyword, and if we're not we just treat the match as text.
Note that the number regexp is very naive, not including strings like `1/2` or `1.5` but including strings like `7up`. I didn't fix it in this PR, but it wouldn't be difficult to do so.

Storyq-12 More Highlighting

---

cypress/e2e/workspace.test.ts
cypress/support/elements/app-elements.ts
src/assets/arrow-icon.svg
src/components/collapse-button.scss
src/components/collapse-button.tsx
src/components/storyq.tsx
src/components/text-pane/text-pane.scss
src/components/text-pane/text-pane.tsx
src/components/text-pane/text-section.scss
src/components/text-pane/text-section.tsx
src/lib/codap-helper.ts
src/stores/store_types_and_constants.ts
src/stores/text_store.ts
src/stores/ui_store.ts
src/storyq.test.tsx

Jira Story: https://concord-consortium.atlassian.net/browse/STORYQ-11
This PR adds a few features to the new text pane. These features have not been finalized or designed yet, so I did my best to make them look decent without spending too much time on appearances. Hopefully this will give the project and design teams an opportunity to try the features to have a better idea of how they could work as they work on final designs.
- Collapse buttons have been added for the main and text panes. These look a bit like CLUE's. Only one of the two panes can be collapsed at any given time.
- A cypress test has been added to test this functionality.
- Text sections in the text pane can now be hidden. Visible text sections will use the space freed up by hidden sections.
- Text section titles now …

Storyq-11 More Text Pane

---

src/stores/store_types_and_constants.ts
src/utilities/utilities.ts

Jira Story: https://concord-consortium.atlassian.net/browse/STORYQ-3
This PR fixes a bug which caused the "not contain" feature to work in the same way as "contain".
- The main problem, which probably was introduced during the major refactor, was caused by keying a dictionary with a `WhereOption` instead of a `SearchWhereOption`. The solution is to include both types as keys in the dictionary.
- A secondary problem was matching `contain: word` without ensuring it was the start of the string, which would also match `not contain: word`.
Note: I started working on this branch thinking it would be for another story, but quickly realized the bug described in STORYQ-3 could be reproduced so switched to fixing it.

Storyq-3 Fix Not Contain

---

package-lock.json
package.json
src/components/text-pane/text-section.tsx
src/components/training_pane.scss
src/lib/codap-helper.ts
src/managers/headings_manager.tsx
src/managers/model_manager.ts
src/managers/notification_manager.ts
src/managers/testing_manager.ts
src/managers/text_feedback_manager.ts
src/stores/domain_store.ts
src/stores/feature_store.ts
src/stores/store_types_and_constants.ts
src/stores/target_store.ts
src/stores/text_store.test.ts
src/types/codap-api-types.ts

Jira stories:
https://concord-consortium.atlassian.net/browse/STORYQ-28
https://concord-consortium.atlassian.net/browse/STORYQ-21
https://concord-consortium.atlassian.net/browse/STORYQ-22
This PR addresses several bugs related to text being displayed and highlighted properly at various stages of the StoryQ process. Text should now be displayed and highlighted properly in almost all cases:
- With regular as well as token (single word) features.
- At all stages in the process (after creating features, after training a model, and after testing a model).
- When cases are selected in the feature or text tables.
I ran out of time before I could fix text display when multiple models have been trained and the user is in the test panel. And there are probably other edge cases that still don't work …

Storyq-28 Text Display Bugs

---

src/managers/text_feedback_manager.ts
src/stores/domain_store.ts
src/stores/feature_store.ts

Jira story: https://concord-consortium.atlassian.net/browse/STORYQ-21
This PR fixes a bug where colors for tokens (subfeatures created by "Single Word" features) were no longer updating properly. This was a tricky bug to fix and I learned some other relevant information on the way.
The ultimate cause for this bug is that `featureStore.tokenMap` is explicitly not observable. I hadn't noticed this previously, and it explains why toggling the visibility of a normal feature is responsive, but not for tokens.
I recently introduced `featureStore.caseIdTokenMap` to make it possible to look up tokens by id in O(1) time. (`tokenMap` keys by token, like "ice" or "great".) The problem is that `caseIdTokenMap` was observable, so even though the same token object was being assigned to both …

Storyq-21 Token Colors
